"""add expired at

Revision ID: 0e4595128d40
Revises: 9b0126908542
Create Date: 2025-09-25 06:13:13.334125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e4595128d40'
down_revision: Union[str, None] = '9b0126908542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkup', sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('checkup', sa.Column('discount_percentage', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkup', 'discount_percentage')
    op.drop_column('checkup', 'expired_at')
    # ### end Alembic commands ###
